[package]
  name = "windmill"
  version = "0.1.0"
  edition = "2021"

[dependencies]
  cxx = "1.0.107"
  tokio = { version = "1.32.0", features = [ "full" ] }

[build-dependencies]
  cxx-build = "1.0.107"
